# A simple action usage
name: Build Kernel

on:
  push:
    branches: ["15.0"]
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/burkvt/android_kernel_xiaomi_jason_15
          kernel-dir: kernel
          kernel-branch: "15.0"
          config: jason_defconfig
          arch: arm64
          aosp-gcc: false
          other-gcc64-url: https://github.com/crdroidandroid/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3
          other-gcc64-branch: "15.0"
          aosp-clang: false
          other-clang-url: https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-vortex
          other-clang-branch: "15.0"
          # android-version: 15
          # aosp-clang-version: r522817
          disable-lto: true
          anykernel3: true
          extra-cmd: CC=clang LD=ld.lld
