name: Build Kernel

on:
  push:
    branches:
      - main # 触发条件，这里设置为push到main分支时触发
  pull_request:
    branches:
      - main # 可选：PR到main分支时也触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新版本的Ubuntu环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # 获取代码

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        bc \
        bison \
        build-essential \
        ccache \
        curl \
        flex \
        libncurses5-dev \
        libssl-dev \
        make \
        wget \
        xz-utils \
        zlib1g-dev \
        libelf-dev \
        dwarves \
        gcc-aarch64-linux-gnu \
        g++-aarch64-linux-gnu # 安装编译内核所需的工具和库

    - name: Compile the Kernel
      run: |
        export ARCH=arm64 # 设置架构
        export CROSS_COMPILE=aarch64-linux-gnu- # 设置交叉编译器前缀
        make O=out vendor/jason_defconfig # 配置内核
        make O=out -j$(nproc) # 开始编译，-j参数根据CPU核心数自动调整并发数量

    - name: Upload Artifact
      if: success() # 仅当构建成功时上传制品
      uses: actions/upload-artifact@v2
      with:
        name: kernel-build
        path: out/arch/arm64/boot/Image.gz-dtb # 假设这是生成的内核镜像路径
